# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-09-26 09:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import filer.fields.image


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='googlemap',
            name='info_content',
            field=models.TextField(blank=True, help_text='content help', max_length=255, verbose_name='textbox content'),
        ),
        migrations.AlterField(
            model_name='googlemap',
            name='info_image',
            field=filer.fields.image.FilerImageField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='filer.Image', verbose_name='textbox image'),
        ),
    ]
