# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-09-26 08:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import filer.fields.image
import videos.utils


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cms', '0016_auto_20160608_1535'),
        ('filer', '0006_auto_20160623_1627'),
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='videos_video', serialize=False, to='cms.CMSPlugin')),
                ('css_class', models.CharField(blank=True, default='', max_length=200, verbose_name='css class')),
                ('in_navigation', models.BooleanField(default=False, verbose_name='in navigation')),
                ('is_visible', models.BooleanField(default=True, verbose_name='visible')),
                ('height', models.CharField(blank=True, default='', max_length=100, verbose_name='height')),
                ('width', models.CharField(blank=True, default='', max_length=50, verbose_name='width')),
                ('name', models.CharField(blank=True, default='', max_length=150, verbose_name='title')),
                ('show_name', models.BooleanField(default=True, verbose_name='display title')),
                ('slug', models.SlugField(blank=True, default='', editable=False, max_length=150, verbose_name='slug')),
                ('autoplay', models.BooleanField(default=False, verbose_name='auto play')),
                ('controls', models.BooleanField(default=True, help_text='only youtube', verbose_name='show controls')),
                ('fullscreen', models.BooleanField(default=True, verbose_name='allow fullscreen')),
                ('infos', models.BooleanField(default=True, verbose_name='show infos')),
                ('loop', models.BooleanField(default=False, verbose_name='loop')),
                ('mute', models.BooleanField(default=False, verbose_name='mute')),
                ('abstract', models.TextField(blank=True, default='', max_length=250, verbose_name='abstract')),
                ('description', models.TextField(blank=True, default='', verbose_name='description')),
                ('video_url', models.URLField(blank=True, help_text='youtube & vimeo urls only', null=True, verbose_name='video url')),
                ('image', filer.fields.image.FilerImageField(blank=True, default=None, help_text='placeholder image', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='filer.Image', verbose_name='image')),
            ],
            options={
                'abstract': False,
            },
            bases=(videos.utils.VideoMixin, 'cms.cmsplugin'),
        ),
    ]
