# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-07-18 13:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teasers', '0002_auto_20170718_1434'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teaser',
            name='name',
            field=models.CharField(blank=True, default='', max_length=150, verbose_name='Name'),
        ),
    ]
