# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2016-12-06 11:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sliders', '0004_auto_20161206_1105'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='link',
            name='target',
        ),
    ]
