# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2016-12-06 13:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sliders', '0005_remove_link_target'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='plugin',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='plugin_link', to='cms.CMSPlugin'),
        ),
    ]
