# Generated by Django 2.2.12 on 2020-05-08 19:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pictures', '0003_auto_20181205_1413'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallery',
            name='cms_page',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pictures_gallery_set', to='cms.Page'),
        ),
        migrations.AlterField(
            model_name='picture',
            name='cms_page',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pictures_picture_set', to='cms.Page'),
        ),
    ]
