# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-09-26 08:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cms', '0016_auto_20160608_1535'),
    ]

    operations = [
        migrations.CreateModel(
            name='Column',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='columns_column', serialize=False, to='cms.CMSPlugin')),
                ('css_class', models.CharField(blank=True, default='', max_length=200, verbose_name='css class')),
                ('in_navigation', models.BooleanField(default=False, verbose_name='in navigation')),
                ('is_visible', models.BooleanField(default=True, verbose_name='visible')),
                ('height', models.CharField(blank=True, default='', max_length=100, verbose_name='height')),
                ('width', models.CharField(blank=True, default='', max_length=50, verbose_name='width')),
                ('name', models.CharField(blank=True, default='', max_length=150, verbose_name='title')),
                ('show_name', models.BooleanField(default=True, verbose_name='display title')),
                ('slug', models.SlugField(blank=True, default='', editable=False, max_length=150, verbose_name='slug')),
            ],
            options={
                'abstract': False,
            },
            bases=('cms.cmsplugin',),
        ),
    ]
