# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-12-05 14:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('columns', '0003_column_cms_page'),
    ]

    operations = [
        migrations.AlterField(
            model_name='column',
            name='bg_color',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='bg color'),
        ),
    ]
