# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2016-12-06 11:05
from __future__ import unicode_literals

import cms.models.fields
from django.db import migrations, models
import django.db.models.deletion
import filer.fields.file


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0016_auto_20160608_1535'),
        ('filer', '0006_auto_20160623_1627'),
        ('sliders', '0002_auto_20161206_1004'),
    ]

    operations = [
        migrations.CreateModel(
            name='SliderLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=150, verbose_name='title')),
                ('abstract', models.TextField(blank=True, default='', max_length=250, verbose_name='abstract')),
                ('anchor', models.CharField(blank=True, default='', max_length=150, verbose_name='anchor')),
                ('url', models.URLField(blank=True, default='', max_length=255, verbose_name='URL')),
                ('target', models.CharField(blank=True, default='', max_length=255, verbose_name='target')),
                ('email', models.EmailField(blank=True, default='', max_length=254, verbose_name='Email')),
                ('cms_page', cms.models.fields.PageField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cms.Page', verbose_name='page')),
                ('filer_file', filer.fields.file.FilerFileField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='filer.File', verbose_name='file')),
                ('plugin', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cms.CMSPlugin')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
