# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2016-12-06 11:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sliders', '0003_sliderlink'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SliderLink',
            new_name='Link',
        ),
    ]
