# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-09-26 08:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import filer.fields.image


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cms', '0016_auto_20160608_1535'),
        ('filer', '0006_auto_20160623_1627'),
    ]

    operations = [
        migrations.CreateModel(
            name='GoogleMap',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='maps_googlemap', serialize=False, to='cms.CMSPlugin')),
                ('css_class', models.CharField(blank=True, default='', max_length=200, verbose_name='css class')),
                ('in_navigation', models.BooleanField(default=False, verbose_name='in navigation')),
                ('is_visible', models.BooleanField(default=True, verbose_name='visible')),
                ('height', models.CharField(blank=True, default='', max_length=100, verbose_name='height')),
                ('width', models.CharField(blank=True, default='', max_length=50, verbose_name='width')),
                ('name', models.CharField(blank=True, default='', max_length=150, verbose_name='title')),
                ('show_name', models.BooleanField(default=True, verbose_name='display title')),
                ('slug', models.SlugField(blank=True, default='', editable=False, max_length=150, verbose_name='slug')),
                ('address', models.CharField(max_length=150, verbose_name='address')),
                ('zipcode', models.CharField(max_length=30, verbose_name='zip code')),
                ('city', models.CharField(max_length=100, verbose_name='city')),
                ('info_content', models.TextField(blank=True, help_text='content help', max_length=255, verbose_name='additional content')),
                ('map_type', models.CharField(default='ROADMAP', max_length=40, verbose_name='map type')),
                ('style', models.TextField(blank=True, help_text='google map styles', verbose_name='custom map style')),
                ('zoom', models.PositiveSmallIntegerField(default=14, verbose_name='zoom level')),
                ('lat', models.CharField(blank=True, max_length=20, null=True, verbose_name='latitude')),
                ('lng', models.CharField(blank=True, help_text='lat help', max_length=20, null=True, verbose_name='longitude')),
                ('pan_heading', models.CharField(blank=True, max_length=20, null=True, verbose_name='camera orientation')),
                ('pan_pitch', models.CharField(blank=True, max_length=20, null=True, verbose_name='camera pitch')),
                ('route_planer_title', models.CharField(blank=True, default='Calculate your fastest way to here', max_length=150, null=True, verbose_name='route planner title')),
                ('route_planer', models.BooleanField(default=False, verbose_name='route planner')),
                ('info_window', models.BooleanField(default=True, help_text='Show textbox over marker', verbose_name='info window')),
                ('scrollwheel', models.BooleanField(default=True, help_text='scrollwheel help', verbose_name='scrollwheel')),
                ('double_click_zoom', models.BooleanField(default=True, verbose_name='double click zoom')),
                ('draggable', models.BooleanField(default=True, verbose_name='draggable')),
                ('keyboard_shortcuts', models.BooleanField(default=True, verbose_name='keyboard shortcuts')),
                ('pan_control', models.BooleanField(default=True, verbose_name='Pan control')),
                ('zoom_control', models.BooleanField(default=True, verbose_name='zoom control')),
                ('street_view_control', models.BooleanField(default=True, verbose_name='Street View control')),
                ('info_image', filer.fields.image.FilerImageField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='filer.Image', verbose_name='additional content image')),
            ],
            options={
                'abstract': False,
            },
            bases=('cms.cmsplugin',),
        ),
    ]
