# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-07-18 11:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import filer.fields.file


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cms', '0016_auto_20160608_1535'),
        ('filer', '0007_auto_20161016_1055'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teaser',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='teasers_teaser', serialize=False, to='cms.CMSPlugin')),
                ('name', models.CharField(default='', max_length=150, verbose_name='Name')),
                ('body', models.TextField(blank=True, default='', verbose_name='Text')),
                ('filer_icon', filer.fields.file.FilerFileField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cms_teasers_teaser_filer_icon_set', to='filer.File', verbose_name='Icon')),
            ],
            options={
                'verbose_name': 'Teaser',
                'verbose_name_plural': 'Teasers',
            },
            bases=('cms.cmsplugin',),
        ),
        migrations.CreateModel(
            name='TeaserWrap',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='teasers_teaserwrap', serialize=False, to='cms.CMSPlugin')),
                ('css_class', models.CharField(blank=True, default='', max_length=200, verbose_name='CSS class')),
                ('in_navigation', models.BooleanField(default=False, verbose_name='In navigation')),
                ('is_visible', models.BooleanField(default=True, verbose_name='Visible')),
                ('height', models.CharField(blank=True, default='', max_length=100, verbose_name='Height')),
                ('width', models.CharField(blank=True, default='', max_length=50, verbose_name='Width')),
                ('name', models.CharField(blank=True, default='', max_length=150, verbose_name='Name')),
                ('slug', models.SlugField(blank=True, default='', editable=False, max_length=150, verbose_name='Slug')),
                ('cms_page', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cms_teasers_wrap_set', to='cms.Page')),
            ],
            options={
                'verbose_name': 'Teasers Wrap',
                'verbose_name_plural': 'Teasers Wraps',
            },
            bases=('cms.cmsplugin',),
        ),
    ]
