# Generated by Django 2.2.12 on 2020-05-08 19:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teasers', '0003_auto_20170718_1501'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teaserwrap',
            name='cms_page',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cms_teasers_wrap_set', to='cms.Page'),
        ),
    ]
