# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-12-05 14:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sliders', '0007_slide_name_sub'),
    ]

    operations = [
        migrations.AddField(
            model_name='slide',
            name='bg_color',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='bg color'),
        ),
        migrations.AddField(
            model_name='slider',
            name='bg_color',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='bg color'),
        ),
    ]
