# Generated by Django 2.2.12 on 2020-05-08 19:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sliders', '0008_auto_20181205_1413'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='plugin',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='plugin_link', to='cms.CMSPlugin'),
        ),
        migrations.AlterField(
            model_name='slide',
            name='cms_page',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sliders_slide_set', to='cms.Page'),
        ),
        migrations.AlterField(
            model_name='slider',
            name='cms_page',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sliders_slider_set', to='cms.Page'),
        ),
    ]
