# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-12-06 13:44
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import filer.fields.image


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0016_auto_20160608_1535'),
        ('sliders', '0008_auto_20181205_1413'),
        migrations.swappable_dependency(settings.FILER_IMAGE_MODEL),
        ('sections', '0002_wrap_cms_page'),
    ]

    operations = [
        migrations.CreateModel(
            name='Section',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='sections_section', serialize=False, to='cms.CMSPlugin')),
                ('css_class', models.CharField(blank=True, default='', max_length=200, verbose_name='css class')),
                ('in_navigation', models.BooleanField(default=False, verbose_name='in navigation')),
                ('is_visible', models.BooleanField(default=True, verbose_name='visible')),
                ('height', models.CharField(blank=True, default='', max_length=100, verbose_name='height')),
                ('width', models.CharField(blank=True, default='', max_length=50, verbose_name='width')),
                ('name', models.CharField(blank=True, default='', max_length=150, verbose_name='title')),
                ('show_name', models.BooleanField(default=True, verbose_name='display title')),
                ('slug', models.SlugField(blank=True, default='', editable=False, max_length=150, verbose_name='slug')),
                ('bg_color', models.CharField(blank=True, default='', max_length=50, verbose_name='background color')),
                ('html_tag', models.CharField(default='div', max_length=200, verbose_name='html tag')),
                ('bg_image', filer.fields.image.FilerImageField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sections_section_bg_image_set', to=settings.FILER_IMAGE_MODEL, verbose_name='background image')),
                ('cms_page', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='cms.Page')),
            ],
            options={
                'verbose_name': 'Section',
                'verbose_name_plural': 'Sections',
            },
            bases=('cms.cmsplugin',),
        ),
        migrations.RemoveField(
            model_name='wrap',
            name='bg_image',
        ),
        migrations.RemoveField(
            model_name='wrap',
            name='cms_page',
        ),
        migrations.RemoveField(
            model_name='wrap',
            name='cmsplugin_ptr',
        ),
        migrations.DeleteModel(
            name='Wrap',
        ),
    ]
