# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-12-06 12:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sites', '0002_alter_domain_unique'),
    ]

    operations = [
        migrations.CreateModel(
            name='CMSPluginConf',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plugin_name', models.CharField(default='', max_length=100, verbose_name='Plugin')),
                ('fieldsets', models.TextField(blank=True, default='{}', verbose_name='Fieldsets')),
                ('required_fields', models.TextField(blank=True, default='{}', verbose_name='Fieldsets')),
            ],
            options={
                'ordering': ['site_conf', 'plugin_name'],
                'verbose_name': 'Plugin',
                'verbose_name_plural': 'Plugins',
            },
        ),
        migrations.CreateModel(
            name='CMSPluginSiteConf',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site', models.OneToOneField(default=1, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sites.Site')),
            ],
            options={
                'ordering': ['site', 'id'],
                'verbose_name': 'Settings',
                'verbose_name_plural': 'Settings',
            },
        ),
        migrations.AddField(
            model_name='cmspluginconf',
            name='site_conf',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cmsplugins.CMSPluginSiteConf'),
        ),
    ]
