# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-09-26 08:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import filer.fields.image


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cms', '0016_auto_20160608_1535'),
        ('filer', '0006_auto_20160623_1627'),
    ]

    operations = [
        migrations.CreateModel(
            name='Header',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='headers_header', serialize=False, to='cms.CMSPlugin')),
                ('css_class', models.CharField(blank=True, default='', max_length=200, verbose_name='css class')),
                ('in_navigation', models.BooleanField(default=False, verbose_name='in navigation')),
                ('is_visible', models.BooleanField(default=True, verbose_name='visible')),
                ('height', models.CharField(blank=True, default='', max_length=100, verbose_name='height')),
                ('width', models.CharField(blank=True, default='', max_length=50, verbose_name='width')),
                ('name', models.CharField(blank=True, default='', max_length=150, verbose_name='title')),
                ('show_name', models.BooleanField(default=True, verbose_name='display title')),
                ('slug', models.SlugField(blank=True, default='', editable=False, max_length=150, verbose_name='slug')),
                ('abstract', models.TextField(blank=True, default='', max_length=250, verbose_name='abstract')),
                ('description', models.TextField(blank=True, default='', max_length=250, verbose_name='descrition')),
                ('text_position', models.CharField(blank=True, default='', max_length=100, verbose_name='text position')),
                ('text_color', models.CharField(blank=True, default='', max_length=100, verbose_name='text color')),
                ('image', filer.fields.image.FilerImageField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='filer.Image', verbose_name='image')),
            ],
            options={
                'abstract': False,
            },
            bases=('cms.cmsplugin',),
        ),
    ]
