# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-07-18 10:32
from __future__ import unicode_literals

from django.db import migrations
import django.db.models.deletion
import filer.fields.image


class Migration(migrations.Migration):

    dependencies = [
        ('sections', '0003_auto_20170718_1148'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='section',
            options={'verbose_name': 'Section', 'verbose_name_plural': 'Sections'},
        ),
        migrations.AlterField(
            model_name='section',
            name='bg_image',
            field=filer.fields.image.FilerImageField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sections_section_bg_image_set', to='filer.Image', verbose_name='background image'),
        ),
    ]
