# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-12-05 10:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sites', '0002_alter_domain_unique'),
    ]

    operations = [
        migrations.CreateModel(
            name='CMSPluginConf',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site', models.OneToOneField(default=1, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sites.Site')),
            ],
            options={
                'ordering': ['site', 'id'],
                'verbose_name': 'CMS-Plugins settings',
                'verbose_name_plural': 'CMS-Plugins settings',
            },
        ),
    ]
