# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-12-05 12:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cmspluginconf',
            options={'ordering': ['site', 'id'], 'verbose_name': 'Settings', 'verbose_name_plural': 'Settings'},
        ),
        migrations.AddField(
            model_name='cmspluginconf',
            name='settings',
            field=models.TextField(blank=True, default='{}', verbose_name='Plugin settings'),
        ),
    ]
