# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-12-05 12:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_auto_20181205_1217'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cmspluginconf',
            old_name='settings',
            new_name='json',
        ),
    ]
