# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-12-05 12:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_auto_20181205_1238'),
    ]

    operations = [
        migrations.CreateModel(
            name='CMSPluginConf',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plugin_name', models.CharField(default='', max_length=100, verbose_name='Plugin')),
                ('conf_str', models.TextField(blank=True, default='{}', verbose_name='Settings')),
            ],
            options={
                'ordering': ['site_conf', 'plugin_name'],
                'verbose_name': 'Plugin',
                'verbose_name_plural': 'Plugins',
            },
        ),
        migrations.RemoveField(
            model_name='cmspluginsiteconf',
            name='json',
        ),
        migrations.AddField(
            model_name='cmspluginconf',
            name='site_conf',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.CMSPluginSiteConf'),
        ),
    ]
